# Generated by Django 3.2.4 on 2021-08-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='teste',
        ),
        migrations.AddField(
            model_name='user',
            name='país',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
