# Generated by Django 3.2.4 on 2021-08-31 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210830_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='país',
            new_name='pais',
        ),
    ]
