# Generated by Django 3.2.4 on 2021-09-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210908_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='code',
        ),
    ]
