# Generated by Django 3.2.4 on 2021-09-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sala_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sala',
        ),
    ]
