# Generated by Django 3.2.4 on 2021-09-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='rzq3229vvdpcp3pl', max_length=16, primary_key=True, serialize=False),
        ),
    ]
