# Generated by Django 3.2.4 on 2021-09-22 12:07

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210922_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userCode',
            field=models.CharField(default=main.models.ramCode, max_length=10),
        ),
    ]
