# Generated by Django 3.2.4 on 2021-09-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='8fzwprwfvb866a3x', max_length=16, primary_key=True, serialize=False),
        ),
    ]
