# Generated by Django 3.2.4 on 2021-09-21 00:01

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=10)),
                ('pieces', models.CharField(default=' rwa1 cwb1 bwc1 qwd1 kwe1 bwf1 cwg1 rwh1 pwa2 pwb2 pwc2 pwd2 pwe2 pwf2 pwg2 pwh2 pba7 pbb7 pbc7 pbd7 pbe7 pbf7 pbg7 pbh7 rba8 cbb8 qbd8 kbe8 bbf8 cbg8 rbh8', max_length=155)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
