# Generated by Django 3.2.4 on 2021-09-20 18:59

from django.db import migrations, models
import main.views


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210920_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='nome',
            field=models.CharField(default='sala', max_length=100),
        ),
        migrations.AlterField(
            model_name='sala',
            name='code',
            field=models.CharField(default=main.views.ramCode, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='cseueso9da3a8c23', max_length=16, primary_key=True, serialize=False),
        ),
    ]
