# Generated by Django 3.2.4 on 2021-09-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210920_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='6r4baq7l8sl695xm', max_length=16, primary_key=True, serialize=False),
        ),
    ]
