# Generated by Django 3.2.4 on 2021-09-20 19:04

from django.db import migrations, models
import main.views


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='code',
        ),
        migrations.AlterField(
            model_name='sala',
            name='id',
            field=models.CharField(default=main.views.ramCode, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=main.views.ramCode, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
