# Generated by Django 3.2.4 on 2021-09-29 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210929_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('1e7d00fa-b20f-41bd-bdb9-48d3d755d6f4'), unique=True),
        ),
    ]
