# Generated by Django 3.2.4 on 2021-09-28 23:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210928_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('317e7ec4-6733-4d88-b242-d6c709f2d645'), unique=True),
        ),
    ]
