# Generated by Django 3.2.4 on 2021-09-29 12:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210928_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.UUIDField(default=uuid.UUID('d4990c4a-2120-11ec-b983-6432a83d5bc0'), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='room', to='main.room'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('e42d5b5b-e714-4730-9aae-65a991d0e3df'), unique=True),
        ),
    ]
