# Generated by Django 3.2.4 on 2021-09-29 12:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210929_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.UUIDField(default=uuid.UUID('61b44c8b-9f30-4321-97b2-649b9873986d'), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('6dd98066-25ce-42e4-9f6e-47dd95f09c36'), unique=True),
        ),
    ]
