# Generated by Django 3.2.4 on 2021-09-29 12:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210929_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.UUIDField(default=uuid.UUID('564c4ca6-0fbe-48ee-a5ff-67f21c16e764'), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='room',
            field=models.ForeignKey(default='Room.code', on_delete=django.db.models.deletion.CASCADE, related_name='room', to='main.room'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('c807fe61-c10a-467f-82cf-74b8e4307185'), unique=True),
        ),
    ]
