# Generated by Django 3.2.4 on 2021-09-29 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210929_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.UUIDField(default=uuid.UUID('51092ce2-010b-4bca-8bd9-2e2b829e50db'), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('5f08f916-3ccd-404b-a660-d6ecbe1f5630'), unique=True),
        ),
    ]
