# Generated by Django 3.2.4 on 2021-09-29 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210929_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='code',
        ),
        migrations.AddField(
            model_name='room',
            name='roomCode',
            field=models.UUIDField(default=uuid.UUID('d94d6f53-c163-4feb-8707-aa6830c30404'), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('7fec9f33-b493-45a8-9652-75eb93498a10'), unique=True),
        ),
    ]
