# Generated by Django 3.2.4 on 2021-09-29 17:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210929_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relógio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveIntegerField()),
                ('zero', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='roomCode',
            field=models.UUIDField(default=uuid.UUID('d9797d49-71f5-4d58-ac3c-ab5cd998721f'), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('12ad2398-a8a7-4946-8564-e19177b10048'), unique=True),
        ),
    ]
