# Generated by Django 3.2.4 on 2021-09-29 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210929_1433'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relógio',
            new_name='Relogio',
        ),
        migrations.AlterField(
            model_name='room',
            name='roomCode',
            field=models.UUIDField(default=uuid.UUID('2283f629-a4d7-4842-81c5-2c85d60fda52'), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('61e1428f-0338-476c-a18b-196ea4aebf28'), unique=True),
        ),
    ]
