# Generated by Django 3.2.4 on 2021-09-29 17:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210929_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relogio',
            name='zero',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomCode',
            field=models.UUIDField(default=uuid.UUID('cc147725-f120-4f44-8249-5161d2d275ef'), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('23112cbc-82fc-4a51-8df2-20dec579ed27'), unique=True),
        ),
    ]
