# Generated by Django 3.2.4 on 2021-09-29 21:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210929_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relogio',
            name='time',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomCode',
            field=models.UUIDField(default=uuid.UUID('6f4d4e9a-f3bd-44fc-a9dc-eeb6ca6423e3'), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='room',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='room', to='main.room'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('fa48faa4-7761-4d3b-837a-321d098688f9'), unique=True),
        ),
    ]
