# Generated by Django 3.2.4 on 2021-09-29 22:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20210929_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomCode',
            field=models.UUIDField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('18f53f43-9b78-4219-87f8-5f0bd8101045'), unique=True),
        ),
    ]
