# Generated by Django 3.2.4 on 2021-09-29 22:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210929_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('5973368c-2b47-4659-b5d9-68a729d4928c'), unique=True),
        ),
    ]
