# Generated by Django 3.2.4 on 2021-09-29 22:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20210929_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('24ca66cb-0bbf-416c-85c9-4dae9dba34dc'), unique=True),
        ),
    ]
