# Generated by Django 3.2.4 on 2021-09-29 22:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_user_usercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomCode',
            field=models.UUIDField(default=uuid.UUID('506b8fec-f518-40d9-a424-1f32cf998db1'), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='main.room'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('5a95ac03-9e53-40a6-ae67-31340d62443a'), unique=True),
        ),
    ]
