# Generated by Django 3.2.4 on 2021-09-29 22:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20210929_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomCode',
            field=models.UUIDField(default=uuid.UUID('155b0c44-ac41-4ee1-98f7-6b848b23e0f0'), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('a5f44c25-5de9-40b5-9ed3-6b5455f18db5'), unique=True),
        ),
    ]
