# Generated by Django 3.2.4 on 2021-09-29 22:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20210929_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomCode',
            field=models.UUIDField(default=uuid.UUID('56624dc4-78e3-4ce5-8b34-de20a41ab792'), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('971c08bc-3bd1-4f6d-918a-4358c86f1a57'), unique=True),
        ),
    ]
