# Generated by Django 3.2.4 on 2021-09-29 22:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20210929_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomCode',
            field=models.UUIDField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('f0d119ca-3034-4aeb-af7b-facbc9462e97'), unique=True),
        ),
    ]
