# Generated by Django 3.2.4 on 2021-09-29 22:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20210929_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('43cc9dc1-ae88-45c3-bb5c-9ac2acb5c0a2'), unique=True),
        ),
    ]
