# Generated by Django 3.2.4 on 2021-09-29 22:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_user_usercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomCode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('5aee2bc5-de1f-4749-a7c1-912970a8f27e'), unique=True),
        ),
    ]
