# Generated by Django 3.2.4 on 2021-09-29 22:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20210929_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('f95c4337-fd3e-4d06-8eca-d0bf2ea9fa7e'), unique=True),
        ),
    ]
