# Generated by Django 3.2.4 on 2021-09-29 22:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_user_usercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomCode',
            field=models.UUIDField(default=uuid.UUID('fac1f3a4-aafe-4df6-9a55-c0d79ba62a19'), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('45754dac-e7bc-4402-8025-b410d6bbb1a0'), unique=True),
        ),
    ]
