# Generated by Django 3.2.4 on 2021-09-29 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_user_usercode'),
        ('main', '0047_alter_user_usercode'),
    ]

    operations = [
    ]
