# Generated by Django 3.2.4 on 2021-09-30 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20210929_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomCode',
            field=models.UUIDField(default=uuid.UUID('54f4bea8-0e7d-4796-a5d0-86472e6a723c'), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('12aa357c-db76-4d28-9625-229f500ac907'), unique=True),
        ),
    ]
