# Generated by Django 3.2.4 on 2021-09-30 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_merge_20210930_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomCode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('ac82e7ec-2398-4724-bf80-cfc7e067e7a4'), unique=True),
        ),
    ]
