# Generated by Django 3.2.4 on 2021-10-01 00:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20210930_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user1',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='room',
            name='user2',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('e0395278-20d9-482a-bdff-45ee152765f7'), unique=True),
        ),
    ]
