# Generated by Django 3.2.4 on 2021-09-30 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20210930_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('d1c8875c-4d31-49cb-bca7-41ea35c56769'), unique=True),
        ),
    ]
