# Generated by Django 3.2.4 on 2021-09-30 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_user_usercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomCode',
            field=models.UUIDField(default=uuid.UUID('d09a3176-80f6-4d1a-b8d0-c2a3d05ca6fc'), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('ef76f4b5-ff61-481e-b93d-6d770793f48f'), unique=True),
        ),
    ]
