# Generated by Django 3.2.4 on 2021-10-01 01:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20210930_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='whoMove',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('4362ee99-fc97-4d9c-b52a-b0ff12caf1f5'), unique=True),
        ),
    ]
