# Generated by Django 3.2.4 on 2021-09-30 15:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20210930_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomCode',
            field=models.UUIDField(default=uuid.UUID('9f5a2fa3-2e96-4532-bd13-9b7b67df0fe5'), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('d970268a-3d5d-4f06-88e7-4f0ffeab5d78'), unique=True),
        ),
    ]
