# Generated by Django 3.2.4 on 2021-09-30 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20210930_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomCode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('0a76e0ad-4f96-400d-b789-53a3cb6ae15e'), unique=True),
        ),
    ]
