# Generated by Django 3.2.4 on 2021-09-30 20:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20210930_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomCode',
            field=models.CharField(default=uuid.UUID('e0ee503e-6579-4f64-a00d-af9b3e7d4f9b'), max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('74877e26-a761-4d3c-ae74-05cfa8a07859'), unique=True),
        ),
    ]
