# Generated by Django 3.2.4 on 2021-09-30 20:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_auto_20210930_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomCode',
            field=models.CharField(default=uuid.UUID('3aae8a92-76be-4063-abc0-b826b4ea9544'), max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('bbc34e7a-8895-4fb3-9d3f-25a4c9365186'), unique=True),
        ),
    ]
