# Generated by Django 3.2.4 on 2021-10-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20211001_1012'),
        ('main', '0058_auto_20210930_1737'),
    ]

    operations = [
    ]
