# Generated by Django 3.2.4 on 2021-10-11 01:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_auto_20211010_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomName', models.CharField(default='', max_length=10, unique=True)),
                ('user1', models.CharField(default='', max_length=150)),
                ('user2', models.CharField(default='', max_length=150)),
                ('timer1', models.SmallIntegerField(default=600)),
                ('timer2', models.SmallIntegerField(default=600)),
                ('history', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='user1',
        ),
        migrations.AlterField(
            model_name='room',
            name='roomCode',
            field=models.CharField(default=uuid.UUID('34f19b7a-97b7-4610-a06b-bac390cc0521'), max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='tempTimer',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('b7f8b67e-1297-4add-91aa-416301c8ef65'), unique=True),
        ),
    ]
