# Generated by Django 3.2.4 on 2021-10-11 01:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20211010_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user1',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomCode',
            field=models.CharField(default=uuid.UUID('ac25bf93-e8e9-4426-abf8-522d0f6322e0'), max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('00921ccb-ce14-479c-9a4c-09e2a668db9d'), unique=True),
        ),
    ]
