# Generated by Django 3.2.4 on 2021-10-14 23:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_auto_20211010_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='result',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomCode',
            field=models.CharField(default=uuid.UUID('9a78281e-8ad9-4520-968f-dcddb95ad8b4'), max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.UUID('08214aa3-285c-4c1c-93af-c15ccfeccb96'), unique=True),
        ),
    ]
