# Generated by Django 3.2.4 on 2021-10-16 16:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_auto_20211014_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomCode',
            field=models.CharField(default=uuid.UUID('5b8acfa8-0ab7-4386-9c51-02023390f7aa'), max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userCode',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
